name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          check-latest: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies.
        run: 'npm i -D'

      - name: Run tests.
        run: 'npm run test'
      
      - name: Build package.
        run: 'npm run build_all'

      - name: Publish package.
        run: 'npm publish --access=public'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}